version: '3.4'

services:
  panther_lights_controller:
    build:
      context: .
    runtime: nvidia
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1"
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,display
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - type: bind
        source: ./src/panther_description
        target: /ros_ws/src/panther_description
    command: roslaunch panther_description panther_rviz.launch
    # command: xacro /ros_ws/src/panther_description/urdf/panther.urdf.xacro