front_wheels:
  mass: 0.3
  inertia: {ixx: 0.00009165, ixy: 0.00000598, ixz: -0.00000180,
                             iyy: 0.00003309, iyz: -0.00001473,
                                              izz:  0.00008256}
  diameter: 0.2
  lateral_friction: 0.93
  spinning_friction: 0.20
  contact_stiffness: 10000000.0
  contact_damping: 1.0
  visual_mesh: wheel.stl
  collision_mesh: wheel.stl
  color_rgb: "0.15 0.15 0.15"

rear_wheels:
  mass: 0.3
  inertia: {ixx: 0.00009165, ixy: 0.00000598, ixz: -0.00000180,
                             iyy: 0.00003309, iyz: -0.00001473,
                                              izz:  0.00008256}
  diameter: 0.3
  lateral_friction: 0.93
  spinning_friction: 0.20
  contact_stiffness: 10000000.0
  contact_damping: 1.0
  visual_mesh: wheel.stl
  collision_mesh: wheel.stl
  color_rgb: "0.15 0.15 0.15"