front_wheels:
  mass: 0.3
  inertia: {ixx: 1, ixy: 0, ixz: 0,
                    iyy: 1, iyz: 0,
                            izz: 1}
  diameter: 0.2
  lateral_friction: 0.93
  spinning_friction: 0.20
  contact_stiffness: 10000000.0
  contact_damping: 1.0
  visual_mesh: wheel.stl
  collision_mesh: wheel.stl
  color: DarkGrey

rear_wheels:
  mass: 0.3
  inertia: {ixx: 1, ixy: 0, ixz: 0,
                    iyy: 1, iyz: 0,
                            izz: 1}
  diameter: 0.3
  lateral_friction: 0.93
  spinning_friction: 0.20
  contact_stiffness: 10000000.0
  contact_damping: 1.0
  visual_mesh: wheel.stl
  collision_mesh: wheel.stl
  color: DarkGrey

simulation:
  driver: skid_steer_drive_controller