wheels:
  mass: 3
  inertia: {ixx: 1, ixy: 0, ixz: 0,
                    iyy: 1, iyz: 0,
                            izz: 1}
  diameter: 0.1825
  lateral_friction: 2.93
  spinning_friction: 1.20
  contact_stiffness: 10000000.0
  contact_damping: 1.0
  visual_mesh_left: left_wheel.stl
  visual_mesh_right: right_wheel.stl
  collision_mesh: wheel.stl
  color: DarkGrey

simulation:
  driver: libgazebo_ros_skid_steer_drive