body:
  mass: 43
  inertia: {ixx: 3.364000, ixy: -0.023480, ixz: 0.052320,
                           iyy:  3.151000, iyz: 0.009337,
                                           izz: 5.899000}
  visual:
    cover:
      mesh: cover.stl
      color: Red
    base:
      mesh: body.stl
      color: White
    rails:
      mesh: rails.stl
      color: Black
  collision:
    mesh: body_collision.stl

motors:
  max_torque: 60
  max_velocity: 2
  joint_damping: 0.0
  joint_friction: 0.0
