<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- wheel defining macro -->
  <xacro:macro name="wheel" params="wheel_props prefix">

    <xacro:property name="wheel_separation_x" value="0.44" />

    <xacro:property name="rpy" value="0 0 0" />
    <xacro:if value="${prefix == 'front_left'}">
      <xacro:property name="x" value="${wheel_separation_x/2.0}" />
      <xacro:property name="y" value="${wheel_props['wheel_separation']/2.0}" />
      <xacro:if value="${wheel_props['kinematics'] == 'classic'}">
        <xacro:property name="mesh"
          value="file://$(find ${wheel_props['mesh_package']})/${wheel_props['folder_path']}/wheel_a.dae" />
      </xacro:if>
      <xacro:if value="${wheel_props['kinematics'] == 'mecanum'}">
        <xacro:property name="mesh"
          value="file://$(find ${wheel_props['mesh_package']})/${wheel_props['folder_path']}/wheel_a.dae" />
      </xacro:if>
    </xacro:if>
    <xacro:if value="${prefix == 'front_right'}">
      <xacro:property name="x" value="${wheel_separation_x/2.0}" />
      <xacro:property name="y" value="-${wheel_props['wheel_separation']/2.0}" />
      <xacro:if value="${wheel_props['kinematics'] == 'classic'}">
        <xacro:property name="mesh"
          value="file://$(find ${wheel_props['mesh_package']})/${wheel_props['folder_path']}/wheel_b.dae" />
      </xacro:if>
      <xacro:if value="${wheel_props['kinematics'] == 'mecanum'}">
        <xacro:property name="mesh"
          value="file://$(find ${wheel_props['mesh_package']})/${wheel_props['folder_path']}/wheel_b.dae" />
      </xacro:if>
    </xacro:if>
    <xacro:if value="${prefix == 'rear_left'}">
      <xacro:property name="x" value="-${wheel_separation_x/2.0}" />
      <xacro:property name="y" value="${wheel_props['wheel_separation']/2.0}" />
      <xacro:if value="${wheel_props['kinematics'] == 'classic'}">
        <xacro:property name="mesh" 
          value="file://$(find ${wheel_props['mesh_package']})/${wheel_props['folder_path']}/wheel_a.dae" />
      </xacro:if>
      <xacro:if value="${wheel_props['kinematics'] == 'mecanum'}">
        <xacro:property name="mesh"
          value="file://$(find ${wheel_props['mesh_package']})/${wheel_props['folder_path']}/wheel_c.dae" />
      </xacro:if>
    </xacro:if>
    <xacro:if value="${prefix == 'rear_right'}">
      <xacro:property name="x" value="-${wheel_separation_x/2.0}" />
      <xacro:property name="y" value="-${wheel_props['wheel_separation']/2.0}" />
      <xacro:if value="${wheel_props['kinematics'] == 'classic'}">
        <xacro:property name="mesh"
          value="file://$(find ${wheel_props['mesh_package']})/${wheel_props['folder_path']}/wheel_b.dae" />
      </xacro:if>
      <xacro:if value="${wheel_props['kinematics'] == 'mecanum'}">
        <xacro:property name="mesh"
          value="file://$(find ${wheel_props['mesh_package']})/${wheel_props['folder_path']}/wheel_d.dae" />
      </xacro:if>
    </xacro:if>


    <link name="${prefix}_wheel_link">
       <visual>
        <geometry>
            <mesh filename="${mesh}" scale="1.0 1.0 1.0" />
        </geometry>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
      </visual>

      <collision>
        <geometry>
            <mesh filename="file://$(find ${wheel_props['mesh_package']})/${wheel_props['folder_path']}/collision.stl" scale="1.0 1.0 1.0" />
        </geometry>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
      </collision>

      <inertial>
          <mass value="${wheel_props['mass']}" />
          <inertia ixx="${wheel_props['inertia']['ixx']}"
                   ixy="${wheel_props['inertia']['ixy']}"
                   ixz="${wheel_props['inertia']['ixz']}"
                   iyy="${wheel_props['inertia']['iyy']}"
                   iyz="${wheel_props['inertia']['iyz']}"
                   izz="${wheel_props['inertia']['izz']}" />
      </inertial>
    </link>

    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="body_link" />
      <child link="${prefix}_wheel_link" />
      <origin xyz="${x} ${y} 0.0" rpy="0.0 0.0 0.0" />
      <axis xyz="0.0 1.0 0.0" />

      <limit effort="34.5"
             velocity="2.0" />

      <dynamics damping="0.01"
                friction="0.01"/>
    </joint>
    
  </xacro:macro>

</robot>