global_costmap:
  update_frequency: 1.5
  publish_frequency: 1.5
  transform_tolerance: 0.5
  rolling_window: false
  inflation_radius: 2.5
  resolution: 0.01

  plugins: 
    - {name: static_map,       type: "costmap_2d::StaticLayer"}
      
  static_map:
    lethal_cost_threshold: 115