local_costmap:
  update_frequency: 2.5
  publish_frequency: 2.5
  transform_tolerance: 0.25
  static_map: false
  rolling_window: true
  width: 8
  height: 8
  origin_x: -4.0
  origin_y: -4.0
  resolution: 0.01
  inflation_radius: 1.0
