TebLocalPlannerROS:
  odom_topic: odom

  # Trajectory

  teb_autosize: True
  dt_ref: 0.35
  dt_hysteresis: 0.05
  global_plan_overwrite_orientation: False
  allow_init_with_backwards_motion: True
  max_global_plan_lookahead_dist: 2.5
  feasibility_check_no_poses: 5
  exact_arc_length: False
  # Robot

  max_vel_x: 0.4
  max_vel_x_backwards: 0.4
  max_vel_theta: 0.5
  acc_lim_x: 0.15
  acc_lim_theta: 0.2
  min_turning_radius: 0.0 # diff-drive robot (can turn on place!)
  wheelbase: 0.0

  footprint_model:
    type: "polygon"
    vertices: [[-0.16, 0.38], [0.60, 0.38], [0.60, -0.38], [-0.16, -0.38]] 
    # type: "line"
    # line_start: [0.0, 0.0]
    # line_end: [0.45, 0.0]

    # type: "two_circles"
    # front_offset: 0.2 # for type "two_circles"
    # front_radius: 0.3 # for type "two_circles"
    # rear_offset: 0.1 # for type "two_circles"
    # rear_radius: 0.3 # for type "two_circles"

  # GoalTolerance

  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.2
  free_goal_vel: False

  # Obstacles

  min_obstacle_dist: 0.02 # This value must also include our robot width
  include_costmap_obstacles: True
  costmap_obstacles_behind_robot_dist: 0.2
  obstacle_poses_affected: 10
  costmap_converter_plugin: "costmap_converter::CostmapToLinesDBSRANSAC"
  costmap_converter_spin_thread: True
  costmap_converter_rate: 2

  # Optimization

  no_inner_iterations: 3
  no_outer_iterations: 2
  optimization_activate: True
  optimization_verbose: False
  penalty_epsilon: 0.05
  weight_max_vel_x: 10
  weight_max_vel_y: 2
  weight_max_vel_theta: 1
  weight_acc_lim_x: 5
  weight_acc_lim_theta: 5
  weight_kinematics_nh: 1000
  weight_kinematics_forward_drive: 0
  weight_kinematics_turning_radius: 10
  weight_optimaltime: 150
  weight_shortest_path: 5.0
  weight_obstacle: 150
  weight_dynamic_obstacle: 10 # not in use yet
  # weight_adapt_factor: 2

  # Homotopy Class Planner

  enable_homotopy_class_planning: True
  enable_multithreading: True
  simple_exploration: False
  max_number_classes: 5
  selection_cost_hysteresis: 1.0
  selection_obst_cost_scale: 1.0
  selection_alternative_time_cost: False
  selection_prefer_initial_plan: 0.5

  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 5
  h_signature_prescaler: 0.5
  h_signature_threshold: 0.1
  obstacle_keypoint_offset: 0.1
  obstacle_heading_threshold: 0.45
  visualize_hc_graph: False

  # Recovery
  oscillation_recovery: False
  shrink_horizon_backup: False
