wheels:
  mass: 2.4
  inertia: {ixx: 0.016496, iyy: 0.010050, izz: 0.010068}
  inertia_y_offset: 0.0
  diameter: 0.2032
  wheel_separation: 0.6785
  mesh_package: panther_description
  folder_path: meshes/WH02
  kinematics: mecanum