name: ROS1 test build

on:
  push:
    branches:
      - 'ros1-devel'
  
jobs:
  catkin-test-build-ubuntu-18-04:
    strategy:
      matrix:
        ros-distro: [melodic]

    runs-on: ubuntu-18.04

    name: ${{ matrix.ros-distro }}-${{ matrix.build-type }}-18-04
    steps:
      - uses: ros-tooling/setup-ros@v0.3
        with:
          required-ros-distributions: ${{ matrix.ros-distro }}
      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: ros_components_description
          target-ros1-distro: ${{ matrix.ros-distro }}
          vcs-repo-file-url: ${PWD}/components.repos
  
  catkin-test-build-ubuntu-20-04:
    strategy:
      matrix:
        ros-distro: [noetic]

    runs-on: ubuntu-20.04

    name: ${{ matrix.ros-distro }}-${{ matrix.build-type }}-20-04
    steps:
      - uses: ros-tooling/setup-ros@v0.3
        with:
          required-ros-distributions: ${{ matrix.ros-distro }}
      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: ros_components_description
          target-ros1-distro: ${{ matrix.ros-distro }}
          vcs-repo-file-url: ${PWD}/components.repos
